# fly.toml app configuration file generated for weaboobot on 2024-02-20T17:59:04-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'weaboobot'
primary_region = 'ewr'

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 2
  processes = ['app']
[http_service.concurrency]
  type = "requests"
  hard_limit = 25
  soft_limit = 20

[checks]
  [checks.bot_tcp_check]
    grace_period = "30s"
    interval = "15s"
    port = 1234
    timeout = "10s"
    type = "tcp"

[[vm]]
  size = 'shared-cpu-1x'
