const SubsToSearch = {
    '4knsfw':
        [
            'nsfw_wallpapers',
            'SexyWallpapers',
            'HighResNSFW',
            'nsfw_hd',
            'UHDnsfw'
        ],
    "ahegao":
        [
         'ahegao'
        ],
    'amateur':
        [
            'RealGirls',
            'amateur',
            'gonewild'

        ],

    'nsfw':
        [
            'nsfw',
            'porn',
            'BonerMaterial',
            'adorableporn',
            'nsfw2',
            'Sexy',
            'NSFW_nospam'
        ],
    'artsyporn':
        [
            'SexyButNotPorn'
        ],
    'asian':
        [
            'AsianHotties',
            'juicyasians',
            'asianbabes'
        ],
    'bara':
        [
            'baramanga'
        ],
    'bdsm':
        [
            'bdsm',
            'bondage'
        ],
    'bondage':
        [
            'hentaibondage'
        ],
    'cosplay':
        [
            'nsfwcosplay',
            'cosplayonoff',
            'cosporn',
            'cosplayboobs'
        ],
    'ecchi':
        [
            'ecchi'
        ],
    'futa':
        [
            'futanari'
        ],
    'grool':
        [
            'grool'
        ],
    'hentai':
        [
            'hentai',
            'rule34',
            'HQHentai'
        ],
    'hentaigif':
        [
            'HENTAI_GIF'
        ],
    'hentaiirl':
        [
            'hentai_irl'
        ],
    'lingerie':
        [
            'lingerie',
            'stockings',
            'pantyfetish',
            'panties'
        ],
    'monstergirl':
        [
            'MonsterGirl'
        ],
    'nsfwgif':
        [
            'NSFW_GIF',
            'nsfw_gifs',
            'porninfifteenseconds',
            '60FPSPorn',
            'porn_gifs',
            'nsfw_Best_Porn_Gif',
            'LipsThatGrip',
            'adultgifs'
        ],
    'oppai':
        [
            'OppaiLove'
        ],
    'paizuri':
        [
            'Paizuri'
        ],
    'pantsu':
        [
            'pantsu'
        ],
    'pussy':
        [
            'pussy',
            'rearpussy',
            'simps',
            'vagina',
            'MoundofVenus',
            'PerfectPussies',
            'spreading'
        ],
    'sukebei':
        [
            'Sukebei'
        ],
    'tentacle':
        [
            'tentai'
        ],
    'trap':
        [
            'traphentai'
        ],
    'yaoi':
        [
            'yaoi'
        ],
    'yuri':
        [
            'yuri'
        ],
    'zr':
        [
            'ZettaiRyouiki'
        ],
};

module.exports = {
    SubsToSearch
};
